### ISSUE TITLE
ROS2 foxy and galactic release

### ISSUE THREAD

**Issue by Timple** [introlab/rtabmap-release#1]
Despite the `ros2` branch `rtabmap_ros` is experimental, the `rtabmap` library works fine.

Could it be released for foxy and galactic? (Optionally rolling).

I've verified compilation with colcon already.

**Comment by matlabbe** [comment]
Yes it could, just didn't take time to see if there is a difference between ros1 and ros2 for bloom release on their buildfarm/rosdistro. I will take a look at least for `rtabmap` library.

**Comment by Timple** [comment]
Confirmed to be working using the testing repository on foxy. So thanks for that!

We're actually using galactic. Would you mind releasing for that (and rolling) as well? Now that you're in the release-mode :slightly_smiling_face:

**Comment by matlabbe** [comment]
Yes I tried for galactic and rolling, got some errors:
```
<== Failed
Could not resolve rosdep key 'libopenni-dev' for distro '8':
No definition of [libopenni-dev] for OS [rhel]
	rosdep key : libopenni-dev
	OS name    : rhel
	OS version : 8
	Data:
arch:
		- openni
		debian:
		- libopenni-dev
		fedora:
		- openni-devel
		gentoo:
		- dev-libs/OpenNI
		ubuntu:
		- libopenni-dev
		
Failed to resolve libopenni-dev on rhel:8 with: Error running generator: Failed to resolve rosdep key 'libopenni-dev', aborting.
libopenni-dev is depended on by these packages: ['rtabmap']
<== Failed
```

If you look here: https://github.com/ros/rosdistro/blob/636567785646c4d0a53de515673e5935c7e9c6d1/rosdep/base.yaml#L4048-L4053

There is a missing reference for `rhel`. 

Here all system dependencies required:
```
Package 'rtabmap' has dependencies:
Run Dependencies:
  rosdep key           => focal key
  qt_gui_cpp           => ['ros-rolling-qt-gui-cpp']
  libpcl-all-dev       => ['libpcl-dev']
  libsqlite3-dev       => ['libsqlite3-dev']
  zlib                 => ['zlib1g-dev']
  libfreenect-dev      => ['libfreenect-dev']
  libopenni-dev        => ['libopenni-dev']
  cv_bridge            => ['ros-rolling-cv-bridge']
  octomap              => ['ros-rolling-octomap']
  libg2o               => ['ros-rolling-libg2o']
Build and Build Tool Dependencies:
  rosdep key           => focal key
  qt_gui_cpp           => ['ros-rolling-qt-gui-cpp']
  libpcl-all-dev       => ['libpcl-dev']
  libsqlite3-dev       => ['libsqlite3-dev']
  zlib                 => ['zlib1g-dev']
  libfreenect-dev      => ['libfreenect-dev']
  libopenni-dev        => ['libopenni-dev']
  cv_bridge            => ['ros-rolling-cv-bridge']
  proj                 => ['libproj-dev']
  octomap              => ['ros-rolling-octomap']
  libg2o               => ['ros-rolling-libg2o']
  cmake                => ['cmake']

```

I checked for other `rhel` missing deps, it seems that `libfreenect-dev` is also missing. Someone would have to check if `libfreenect-dev` and `libopenni-dev` are available in `rhel`, then add them to rosdistro's `rosdep/base.yaml` file. Otherwise, we would have to remove freenect and openni from package.xml, though I would prefer to keep them to avoid maintaining more configurations.

**Comment by Timple** [comment]
You might just go ahead and release anyway. They are quite supportive with these things. Or they might just be okay if it works only on 80% of the distros. Still more than 0% :slightly_smiling_face:

**Comment by matlabbe** [comment]
Hi, I didn't realized I could just ignore the rhel release in bloom (I was following the default answers, which was No to continue if rhel deps were missing): https://discourse.ros.org/t/generating-for-rhel-7-in-ros-2-rolling/18979
Here are the galactic and rolling pull requests:
https://github.com/ros/rosdistro/pull/30371
https://github.com/ros/rosdistro/pull/30372
